replicaCount: 1

image:
  repository: ghcr.io/ConductionNL/docurag
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: [] # e.g. - name: ghcr

service:
  type: ClusterIP
  port: 80
  targetPort: 80

env:
  LOG_LEVEL: INFO
  TOP_K: "5"
  MODEL_NAME: intfloat/multilingual-e5-small
  LLM_NAME: llama-v3p3-70b-instruct
  WEB_CONCURRENCY: "1"
  UVICORN_PORT: "80"

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: docusearch.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

