version: "3.9"
services:
  api:
    build: .
    image: docusearch-api:latest
    container_name: docusearch-api
    ports:
      - "8080:8000"
    environment:
      # Logs and app tuning
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      TOP_K: ${TOP_K:-5}
      MODEL_NAME: ${MODEL_NAME:-intfloat/multilingual-e5-small}
      LLM_NAME: ${LLM_NAME:-llama-v3p3-70b-instruct}
    volumes:
      - ./:/app:ro
      - huggingface-cache:/root/.cache/huggingface
    restart: unless-stopped

volumes:
  huggingface-cache: