name: CI

on:
  push:
    branches: [ "main", "helm" ]
  pull_request:
    branches: [ "main", "helm" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (package + dev tools)
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff black

      - name: Lint (ruff)
        run: ruff check src

      - name: Format check (black)
        run: black --check src

      - name: Build Docker image (no push)
        run: docker build -t docurag-ci:${{ github.sha }} .

